spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost/demo?verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: demo
      password: demo.
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 以下配置均有默认值,可以不设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      # 全局逻辑删除的实体字段名 需要配合 @TableLogic 注解
      logic-delete-field: isDelete
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      id-type: assign_id
object-storage:
  type: minio
  minio:
    endpoint: https://demo.ak47007.com
    bucket: demo
    accessKey: demo
    secretKey: demo
